# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -fopenmp   -std=gnu++11

CXX_DEFINES = 

CXX_INCLUDES = -isystem /home/cshao/dev/agt/build/fovea-prefix/src/fovea/FoveaRenderLib -isystem /home/cshao/dev/agt/build/INSTALL/include -I/home/cshao/dev/agt/build/fovea-prefix/src/fovea-build/FoveaRenderLib/../FoveaImagePipelineLib -isystem /home/cshao/dev/agt/build/fovea-prefix/src/fovea/FoveaImagePipelineLib -isystem /usr/local/cuda-8.0/include 

